services:
  - type: web
    name: free-fire-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: "5000"
